# Official envoy extensions used in datafi-edge-server

EXTENSIONS = {
    #
    # For MySQL Connector
    #
    "envoy.filters.network.mysql_proxy":                "@envoy//source/extensions/filters/network/mysql_proxy:config",
    "envoy.filters.network.rbac":                       "@envoy//source/extensions/filters/network/rbac:config",
    "envoy.filters.network.tcp_proxy":                  "@envoy//source/extensions/filters/network/tcp_proxy:config",
    "envoy.upstreams.http.tcp":                         "@envoy//source/extensions/upstreams/http/tcp:config",
    "envoy.transport_sockets.raw_buffer":               "@envoy//source/extensions/transport_sockets/raw_buffer:config",


    #
    # Common
    #
    # "envoy.access_loggers.stdoutput":                   "@envoy//source/extensions/access_loggers/stdoutput:config"
}

EXTENSION_CONFIG_VISIBILITY = ["//:extension_config"]
EXTENSION_PACKAGE_VISIBILITY = ["//:extension_library"]
