static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8090
    filter_chains:
    - filters:
      - name: echo2
        typed_config:
      # - name: envoy.filters.network.http_connection_manager
      #   typed_config:
      #     "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      #     stat_prefix: ingress_http
      #     # access_log:
      #     # - name: envoy.access_loggers.file
      #     #   typed_config:
      #     #     "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
      #     #     path: "/var/log/envoy/ingress_http.log"
      #     #     log_format: {text_format_source: {inline_string: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\"\n"}}
      #     http_filters:
      #     - name: envoy.filters.http.router
      #     route_config:
      #       name: local_route
      #       virtual_hosts:
      #       - name: local_service
      #         domains: ["*"]
      #         routes:
      #         - match:
      #             prefix: "/"
      #           route:
      #             host_rewrite_literal: jsonplaceholder.typicode.com
      #             cluster: service_envoyproxy_io


  clusters:
  - name: service_envoyproxy_io
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: jsonplaceholder.typicode.com
                port_value: 80
    # transport_socket:
    #   name: envoy.transport_sockets.tls
    #   typed_config:
    #     "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    #     sni: jsonplaceholder.typicode.com
